---
# Example showing how to use Secret reference for QNAP Vault address
# This is useful when the address contains sensitive information or credentials
apiVersion: v1
kind: Secret
metadata:
  name: vault-secrets
  namespace: vault
type: Opaque
stringData:
  transit.address: "http://192.168.1.42:61200"
  transit.token: "hvs.EXAMPLE_TOKEN_REPLACE_WITH_YOUR_OWN"
---
apiVersion: vault.homelab.io/v1alpha1
kind: VaultTransitUnseal
metadata:
  name: vault-transit-unseal-secret
  namespace: vault
spec:
  vaultPod:
    namespace: vault
    selector:
      app.kubernetes.io/name: vault
  transitVault:
    # Address is loaded from Secret
    addressFrom:
      secretKeyRef:
        name: vault-secrets
        key: transit.address
    # Token is also from the same Secret
    secretRef:
      name: vault-secrets
      key: transit.token
    keyName: autounseal
    mountPath: transit
    tlsSkipVerify: true
  initialization:
    recoveryShares: 1
    recoveryThreshold: 1
    secretNames:
      adminToken: vault-admin-token
      recoveryKeys: vault-keys
      storeRecoveryKeys: false
      adminTokenAnnotations:
        replicator.v1.mittwald.de/replicate-to-matching: >-
          metadata.annotations.replicator\.v1\.mittwald\.de/replicated-from-version == "2"
  monitoring:
    checkInterval: "30s"
    retryInterval: "10s"
  postUnsealConfig:
    enableKV: true
    enableExternalSecretsOperator: true
    kvConfig:
      path: "secret"
      version: 2
      maxVersions: 5
      deleteVersionAfter: "30d"
    externalSecretsOperatorConfig:
      policyName: "external-secrets-operator"
      kubernetesAuth:
        roleName: "external-secrets-operator"
        serviceAccounts:
          - name: external-secrets
            namespace: external-secrets
        ttl: "24h"
        maxTTL: "24h"