//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressReference) DeepCopyInto(out *AddressReference) {
	*out = *in
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(ConfigMapKeyReference)
		**out = **in
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressReference.
func (in *AddressReference) DeepCopy() *AddressReference {
	if in == nil {
		return nil
	}
	out := new(AddressReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDSpec) DeepCopyInto(out *ArgoCDSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDSpec.
func (in *ArgoCDSpec) DeepCopy() *ArgoCDSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeyReference) DeepCopyInto(out *ConfigMapKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeyReference.
func (in *ConfigMapKeyReference) DeepCopy() *ConfigMapKeyReference {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationStatus) DeepCopyInto(out *ConfigurationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationStatus.
func (in *ConfigurationStatus) DeepCopy() *ConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomCondition) DeepCopyInto(out *CustomCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomCondition.
func (in *CustomCondition) DeepCopy() *CustomCondition {
	if in == nil {
		return nil
	}
	out := new(CustomCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentDependency) DeepCopyInto(out *DeploymentDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentDependency.
func (in *DeploymentDependency) DeepCopy() *DeploymentDependency {
	if in == nil {
		return nil
	}
	out := new(DeploymentDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSecretsOperatorConfig) DeepCopyInto(out *ExternalSecretsOperatorConfig) {
	*out = *in
	in.KubernetesAuth.DeepCopyInto(&out.KubernetesAuth)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSecretsOperatorConfig.
func (in *ExternalSecretsOperatorConfig) DeepCopy() *ExternalSecretsOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalSecretsOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitializationSpec) DeepCopyInto(out *InitializationSpec) {
	*out = *in
	in.SecretNames.DeepCopyInto(&out.SecretNames)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitializationSpec.
func (in *InitializationSpec) DeepCopy() *InitializationSpec {
	if in == nil {
		return nil
	}
	out := new(InitializationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobDependency) DeepCopyInto(out *JobDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobDependency.
func (in *JobDependency) DeepCopy() *JobDependency {
	if in == nil {
		return nil
	}
	out := new(JobDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVConfig) DeepCopyInto(out *KVConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVConfig.
func (in *KVConfig) DeepCopy() *KVConfig {
	if in == nil {
		return nil
	}
	out := new(KVConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesAuthConfig) DeepCopyInto(out *KubernetesAuthConfig) {
	*out = *in
	if in.ServiceAccounts != nil {
		in, out := &in.ServiceAccounts, &out.ServiceAccounts
		*out = make([]ServiceAccountRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesAuthConfig.
func (in *KubernetesAuthConfig) DeepCopy() *KubernetesAuthConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostUnsealConfig) DeepCopyInto(out *PostUnsealConfig) {
	*out = *in
	out.KVConfig = in.KVConfig
	in.ExternalSecretsOperatorConfig.DeepCopyInto(&out.ExternalSecretsOperatorConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostUnsealConfig.
func (in *PostUnsealConfig) DeepCopy() *PostUnsealConfig {
	if in == nil {
		return nil
	}
	out := new(PostUnsealConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretNamesSpec) DeepCopyInto(out *SecretNamesSpec) {
	*out = *in
	if in.AdminTokenAnnotations != nil {
		in, out := &in.AdminTokenAnnotations, &out.AdminTokenAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RecoveryKeysAnnotations != nil {
		in, out := &in.RecoveryKeysAnnotations, &out.RecoveryKeysAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretNamesSpec.
func (in *SecretNamesSpec) DeepCopy() *SecretNamesSpec {
	if in == nil {
		return nil
	}
	out := new(SecretNamesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountRef) DeepCopyInto(out *ServiceAccountRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountRef.
func (in *ServiceAccountRef) DeepCopy() *ServiceAccountRef {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenDependencies) DeepCopyInto(out *TokenDependencies) {
	*out = *in
	if in.Deployments != nil {
		in, out := &in.Deployments, &out.Deployments
		*out = make([]DeploymentDependency, len(*in))
		copy(*out, *in)
	}
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]JobDependency, len(*in))
		copy(*out, *in)
	}
	if in.CustomConditions != nil {
		in, out := &in.CustomConditions, &out.CustomConditions
		*out = make([]CustomCondition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenDependencies.
func (in *TokenDependencies) DeepCopy() *TokenDependencies {
	if in == nil {
		return nil
	}
	out := new(TokenDependencies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenManagementSpec) DeepCopyInto(out *TokenManagementSpec) {
	*out = *in
	in.Dependencies.DeepCopyInto(&out.Dependencies)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenManagementSpec.
func (in *TokenManagementSpec) DeepCopy() *TokenManagementSpec {
	if in == nil {
		return nil
	}
	out := new(TokenManagementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenStatus) DeepCopyInto(out *TokenStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenStatus.
func (in *TokenStatus) DeepCopy() *TokenStatus {
	if in == nil {
		return nil
	}
	out := new(TokenStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitVaultSpec) DeepCopyInto(out *TransitVaultSpec) {
	*out = *in
	if in.AddressFrom != nil {
		in, out := &in.AddressFrom, &out.AddressFrom
		*out = new(AddressReference)
		(*in).DeepCopyInto(*out)
	}
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitVaultSpec.
func (in *TransitVaultSpec) DeepCopy() *TransitVaultSpec {
	if in == nil {
		return nil
	}
	out := new(TransitVaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultPodSpec) DeepCopyInto(out *VaultPodSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultPodSpec.
func (in *VaultPodSpec) DeepCopy() *VaultPodSpec {
	if in == nil {
		return nil
	}
	out := new(VaultPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitUnseal) DeepCopyInto(out *VaultTransitUnseal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitUnseal.
func (in *VaultTransitUnseal) DeepCopy() *VaultTransitUnseal {
	if in == nil {
		return nil
	}
	out := new(VaultTransitUnseal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultTransitUnseal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitUnsealList) DeepCopyInto(out *VaultTransitUnsealList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultTransitUnseal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitUnsealList.
func (in *VaultTransitUnsealList) DeepCopy() *VaultTransitUnsealList {
	if in == nil {
		return nil
	}
	out := new(VaultTransitUnsealList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultTransitUnsealList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitUnsealSpec) DeepCopyInto(out *VaultTransitUnsealSpec) {
	*out = *in
	in.VaultPod.DeepCopyInto(&out.VaultPod)
	in.TransitVault.DeepCopyInto(&out.TransitVault)
	in.Initialization.DeepCopyInto(&out.Initialization)
	out.Monitoring = in.Monitoring
	in.PostUnsealConfig.DeepCopyInto(&out.PostUnsealConfig)
	if in.ArgoCD != nil {
		in, out := &in.ArgoCD, &out.ArgoCD
		*out = new(ArgoCDSpec)
		**out = **in
	}
	if in.TokenManagement != nil {
		in, out := &in.TokenManagement, &out.TokenManagement
		*out = new(TokenManagementSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitUnsealSpec.
func (in *VaultTransitUnsealSpec) DeepCopy() *VaultTransitUnsealSpec {
	if in == nil {
		return nil
	}
	out := new(VaultTransitUnsealSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitUnsealStatus) DeepCopyInto(out *VaultTransitUnsealStatus) {
	*out = *in
	out.ConfigurationStatus = in.ConfigurationStatus
	out.TokenStatus = in.TokenStatus
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitUnsealStatus.
func (in *VaultTransitUnsealStatus) DeepCopy() *VaultTransitUnsealStatus {
	if in == nil {
		return nil
	}
	out := new(VaultTransitUnsealStatus)
	in.DeepCopyInto(out)
	return out
}
