//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationStatus) DeepCopyInto(out *ConfigurationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationStatus.
func (in *ConfigurationStatus) DeepCopy() *ConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSecretsOperatorConfig) DeepCopyInto(out *ExternalSecretsOperatorConfig) {
	*out = *in
	in.KubernetesAuth.DeepCopyInto(&out.KubernetesAuth)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSecretsOperatorConfig.
func (in *ExternalSecretsOperatorConfig) DeepCopy() *ExternalSecretsOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalSecretsOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitializationSpec) DeepCopyInto(out *InitializationSpec) {
	*out = *in
	in.SecretNames.DeepCopyInto(&out.SecretNames)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitializationSpec.
func (in *InitializationSpec) DeepCopy() *InitializationSpec {
	if in == nil {
		return nil
	}
	out := new(InitializationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVConfig) DeepCopyInto(out *KVConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVConfig.
func (in *KVConfig) DeepCopy() *KVConfig {
	if in == nil {
		return nil
	}
	out := new(KVConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesAuthConfig) DeepCopyInto(out *KubernetesAuthConfig) {
	*out = *in
	if in.ServiceAccounts != nil {
		in, out := &in.ServiceAccounts, &out.ServiceAccounts
		*out = make([]ServiceAccountRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesAuthConfig.
func (in *KubernetesAuthConfig) DeepCopy() *KubernetesAuthConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostUnsealConfig) DeepCopyInto(out *PostUnsealConfig) {
	*out = *in
	out.KVConfig = in.KVConfig
	in.ExternalSecretsOperatorConfig.DeepCopyInto(&out.ExternalSecretsOperatorConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostUnsealConfig.
func (in *PostUnsealConfig) DeepCopy() *PostUnsealConfig {
	if in == nil {
		return nil
	}
	out := new(PostUnsealConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretNamesSpec) DeepCopyInto(out *SecretNamesSpec) {
	*out = *in
	if in.AdminTokenAnnotations != nil {
		in, out := &in.AdminTokenAnnotations, &out.AdminTokenAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RecoveryKeysAnnotations != nil {
		in, out := &in.RecoveryKeysAnnotations, &out.RecoveryKeysAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretNamesSpec.
func (in *SecretNamesSpec) DeepCopy() *SecretNamesSpec {
	if in == nil {
		return nil
	}
	out := new(SecretNamesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountRef) DeepCopyInto(out *ServiceAccountRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountRef.
func (in *ServiceAccountRef) DeepCopy() *ServiceAccountRef {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitVaultSpec) DeepCopyInto(out *TransitVaultSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitVaultSpec.
func (in *TransitVaultSpec) DeepCopy() *TransitVaultSpec {
	if in == nil {
		return nil
	}
	out := new(TransitVaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultPodSpec) DeepCopyInto(out *VaultPodSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultPodSpec.
func (in *VaultPodSpec) DeepCopy() *VaultPodSpec {
	if in == nil {
		return nil
	}
	out := new(VaultPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitUnseal) DeepCopyInto(out *VaultTransitUnseal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitUnseal.
func (in *VaultTransitUnseal) DeepCopy() *VaultTransitUnseal {
	if in == nil {
		return nil
	}
	out := new(VaultTransitUnseal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultTransitUnseal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitUnsealList) DeepCopyInto(out *VaultTransitUnsealList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultTransitUnseal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitUnsealList.
func (in *VaultTransitUnsealList) DeepCopy() *VaultTransitUnsealList {
	if in == nil {
		return nil
	}
	out := new(VaultTransitUnsealList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultTransitUnsealList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitUnsealSpec) DeepCopyInto(out *VaultTransitUnsealSpec) {
	*out = *in
	in.VaultPod.DeepCopyInto(&out.VaultPod)
	out.TransitVault = in.TransitVault
	in.Initialization.DeepCopyInto(&out.Initialization)
	out.Monitoring = in.Monitoring
	in.PostUnsealConfig.DeepCopyInto(&out.PostUnsealConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitUnsealSpec.
func (in *VaultTransitUnsealSpec) DeepCopy() *VaultTransitUnsealSpec {
	if in == nil {
		return nil
	}
	out := new(VaultTransitUnsealSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitUnsealStatus) DeepCopyInto(out *VaultTransitUnsealStatus) {
	*out = *in
	out.ConfigurationStatus = in.ConfigurationStatus
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitUnsealStatus.
func (in *VaultTransitUnsealStatus) DeepCopy() *VaultTransitUnsealStatus {
	if in == nil {
		return nil
	}
	out := new(VaultTransitUnsealStatus)
	in.DeepCopyInto(out)
	return out
}
